apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
spec:
  selector:
    matchLabels:
      run: backend-service
  replicas: 1
  template:
    metadata:
      labels:
        run: backend-service
    spec:
      containers:
      - name: backend-service
        image: moconinja/backend-service:MINIKUBE
        ports:
        - containerPort: 8080
        env:
        - name: ACCESS_TOKENS_PATH
          value: "/backend-service/access_tokens.json"
        volumeMounts:
        - name: application-config
          mountPath: "/backend-service/application.properties"
          subPath: "application.properties"
          readOnly: true
        - name: application-tokens
          mountPath: "/backend-service/access_tokens.json"
          subPath: "access_tokens.json"
          readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: backend-service-cm
            items:
            - key: application.properties
              path: application.properties
        - name: application-tokens
          configMap:
            name: backend-service-tokens
            items:
            - key: access_tokens.json
              path: access_tokens.json