apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    run: backend-service
spec:
  selector:
    run: backend-service
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer
