CREATE TABLE SUBSCRIPTIONS
(
	SUBSCRIPTION_ID SERIAL PRIMARY KEY,
	EMAIL VARCHAR ( 50 ) UNIQUE NOT NULL,
	FIRST_NAME VARCHAR ( 50 ),
	GENDER VARCHAR ( 20 ),
	BIRTHDATE DATE NOT NULL,
	CONSENT BOOLEAN NOT NULL,
	NEWSLETTER_ID BIGINT NOT NULL
);

INSERT INTO SUBSCRIPTIONS(EMAIL, FIRST_NAME, GENDER, BIRTHDATE, CONSENT, NEWSLETTER_ID) VALUES ('JohnDoe@fakemail.com', 'John', 'Male', '1990-04-04', TRUE, 1);
INSERT INTO SUBSCRIPTIONS(EMAIL, BIRTHDATE, CONSENT, NEWSLETTER_ID) VALUES ('JaneDoe@fakemail.com', '1990-12-25', TRUE, 2);
