apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      run: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        run: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 5673
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "developer"
        - name: RABBITMQ_DEFAULT_PASS
          value: "developer"