apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    run: rabbitmq
spec:
  ports:
  - port: 5672
    name: "5672"
    protocol: TCP
  - port: 5673
    name: "5673"
    protocol: TCP
  - port: 15672
    name: "15672"
    protocol: TCP
  selector:
    run: rabbitmq