apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  selector:
    matchLabels:
      run: email-service
  replicas: 1
  template:
    metadata:
      labels:
        run: email-service
    spec:
      containers:
      - name: email-service
        image: moconinja/email-service:MINIKUBE
        ports:
        - containerPort: 8082
        volumeMounts:
        - name: application-config
          mountPath: "/email-service/application.properties"
          subPath: "application.properties"
          readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: email-service-cm
            items:
            - key: application.properties
              path: application.properties