apiVersion: v1
kind: ConfigMap
metadata:
  name: email-service-cm
data:
  application.properties: |+
    ###########################################
    # Service's Configuration
    ##########################################
    server.port = 8082
    ###########################################
    # RabbitMQ configuration
    ###########################################
    spring.rabbitmq.host            = rabbitmq
    spring.rabbitmq.port            = 5672
    spring.rabbitmq.username        = developer
    spring.rabbitmq.password        = developer
    spring.rabbitmq.queue.in        = testQueue
    spring.rabbitmq.queue.dlq       = testQueueDLQ
    spring.rabbitmq.exchange        = testExchange
    spring.rabbitmq.routingkey      = testkey
    ###########################################